In [4]:
!pip install numpy pandas
import numpy as np
import pandas as pd

A = np.load("outputs/area_all/A_matrix.npy")
Z = np.load("outputs/area_all/Z_matrix.npy")

region_names = [
    "Trường học (Khu Làng Đại học - ĐH Bách Khoa)",
    "Bệnh viện (Trung tâm Y tế Dĩ An / BV Thủ Đức)",
    "Khu công nghiệp (KCN Sóng Thần 1 & 2)"
]

zone_labels = [
    "commercial",
    "industrial",
    "school",
    "university",
    "hospital",
    "transportation",
    "residential",
    "park"
]

A_df = pd.DataFrame(A, index=region_names, columns=region_names)
Z_df = pd.DataFrame(Z, index=region_names, columns=zone_labels)

display(A_df)
display(Z_df)

Requirement already satisfied: numpy in /home/toon/miniconda3/envs/cityflow_env/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: pandas in /home/toon/miniconda3/envs/cityflow_env/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/toon/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/toon/miniconda3/envs/cityflow_env/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/toon/miniconda3/envs/cityflow_env/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /home/toon/miniconda3/envs/cityflow_env/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,Trường học (Khu Làng Đại học - ĐH Bách Khoa),Bệnh viện (Trung tâm Y tế Dĩ An / BV Thủ Đức),Khu công nghiệp (KCN Sóng Thần 1 & 2)
Trường học (Khu Làng Đại học - ĐH Bách Khoa),0.000000,0.001593,0.001363
Bệnh viện (Trung tâm Y tế Dĩ An / BV Thủ Đức),0.001758,0.000000,0.001944
Khu công nghiệp (KCN Sóng Thần 1 & 2),0.001432,0.001840,0.000000

,commercial,industrial,school,university,hospital,transportation,residential,park
Trường học (Khu Làng Đại học - ĐH Bách Khoa),1,0,1,1,0,1,1,1
Bệnh viện (Trung tâm Y tế Dĩ An / BV Thủ Đức),0,1,1,0,0,1,0,0
Khu công nghiệp (KCN Sóng Thần 1 & 2),0,1,1,0,0,1,1,1